// Package entrypoint provides ABI bindings that are automatically generated by abigen for interacting with
// the EntryPoint contract. The entrypoint directory also contains helper modules for convenience.
package entrypoint
